import { CalendarDays, Check, ChefHat, Clock3, Flame, Home, Lightbulb, Music2, ShieldCheck, Thermometer, Wifi } from 'lucide-react';

type MockupType = 'booking' | 'kitchen' | 'home';

export function InterfaceMockup({ type }: { type: MockupType }) {
  if (type === 'booking') return <div className="scene-card ui-window booking-window"><header><span className="window-dot" /><span className="window-dot" /><span className="window-dot" /><span className="window-name">atelier / agenda</span></header><div className="window-body"><div className="booking-top"><div><small>HOJE / TERÇA</small><strong>Agenda</strong></div><span className="live-pill"><span /> LIVE</span></div><div className="booking-stat"><CalendarDays size={17} /><strong>18</strong><span>reservas confirmadas</span></div><div className="booking-list">{['09:30  João Silva  Corte + barba','11:00  Maria Costa  Corte clássico','14:30  Diogo Alves  Consultoria'].map((item, i) => <div key={item} className="booking-row"><span className={`booking-state state-${i}`} /><span>{item}</span><Check size={14} /></div>)}</div></div></div>;
  if (type === 'kitchen') return <div className="scene-card ui-window kitchen-window"><header><span className="window-dot" /><span className="window-dot" /><span className="window-dot" /><span className="window-name">service / pass</span></header><div className="window-body"><div className="kitchen-top"><div><small>ORDER FLOW</small><strong>Cozinha em movimento</strong></div><Flame className="flame" size={20} /></div><div className="order-card active"><span className="order-number">#042</span><strong>2 × Menu executivo</strong><span className="order-time"><Clock3 size={13} /> 04:32</span><div className="order-progress"><i /></div></div><div className="order-card"><span className="order-number">#043</span><strong>1 × Risotto + água</strong><span className="order-time">na fila</span></div><div className="kitchen-footer"><ChefHat size={15} /> estação quente / sincronizada</div></div></div>;
  return <div className="scene-card ui-window home-window"><header><span className="window-dot" /><span className="window-dot" /><span className="window-dot" /><span className="window-name">habitat / control</span></header><div className="window-body"><div className="home-top"><div><small>CASA 01 / AGORA</small><strong>Bom dia, Tiago.</strong></div><span className="home-status"><Wifi size={13} /> connected</span></div><div className="home-hero-stat"><Thermometer size={19} /><strong>21.5°</strong><span>confortável</span></div><div className="home-controls"><div><Lightbulb size={16} /><span>Luzes</span><b className="toggle-on" /></div><div><Music2 size={16} /><span>Música</span><b className="toggle-off" /></div><div><ShieldCheck size={16} /><span>Segurança</span><b className="toggle-on" /></div></div><div className="home-footer"><Home size={14} /> 12 dispositivos / resposta normal</div></div></div>;
}
